### ISSUE TITLE
Align not working for specific image resolution

### ISSUE THREAD

**Issue by AndreiBaraian** [martin-marek/hdr-plus-pytorch#3]
Hi! First of all, great repository!! 

I stumbled on the following error when doing the inference on a set of 1290x720 burst images. Previously, I've tested on 1920x1080 and it was working fine. Is there any restriction with regard to the image resolution?

The error: 

RuntimeError                              Traceback (most recent call last)
Cell In[7], line 1
----> 1 merged_image = align.align_and_merge(images, device=device)

File ~/work/hdr-plus-pytorch/align.py:283, in align_and_merge(images, ref_idx, device, downscale_factor_list, tile_shape_list, search_region_list)
    281 # iterative improve the alignment in each pyramid layer
    282 for layer_idx in torch.flip(torch.arange(len(ref_pyramid)), [0]):
--> 283     alignment = align_layers(ref_pyramid[layer_idx],
    284                      comp_pyramid[layer_idx],
    285                      tile_shape_list[layer_idx],
    286                      search_region_list[layer_idx],
    287                      alignment,
    288                      downscale_factor_list[min(layer_idx+1, len(ref_pyramid)-1)])
    290 # scale the alignment to the resolution of the original image
    291 alignment = upscale_previous_alignment(alignment, downscale_factor_list[0], W, H)

RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/abandrei/work/hdr-plus-pytorch/align.py", line 161, in align_layers
    # compute coordinates for comparison tiles
    x, y = tile_indices(layer_w, layer_h, tile_w, tile_h, n_tiles_x, n_tiles_y, device) # [n_tiles_y, n_tiles_x, tile_h, tile_w]
    prev_alignment = upscale_previous_alignment(prev_alignment, downscale_factor, n_tiles_x, n_tiles_y) # [2, n_tiles_y, n_tiles_x]
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    x += prev_alignment[0, :, :, None, None]
...
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    if input.dim() == 5 and mode == "nearest":
        return torch._C._nn.upsample_nearest3d(input, output_size, scale_factors)
RuntimeError: Input and output sizes should be greater than 0, but got input (H: 1, W: 1) output (H: 0, W: 1)

**Comment by martin-marek** [comment]
Hi Andrei, thanks for pointing this out!

The issue was that alignment parameters assumed high input resolution. I [changed](https://github.com/martin-marek/hdr-plus-pytorch/commit/322c6039393074cefd9c5082006b509d5121aad1) it so that now the parameters should be automatically set based on input resolution.

Please let me know if it works for you.

**Comment by AndreiBaraian** [comment]
Hi Martin! Nice, now it works like a charm. Thanks a lot!
